name: Pushing README to Dockerhub

on:
  push:
    branches: [ main ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Sync
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: ${{ secrets.DOCKER_USER }}/unturned-egg-openmod
          readme: "./README.md"
